extends Node2D

const BIG_BOMB = preload("res://Assets/Z3/connectors/big_bomb.png")
const BROTHER = preload("res://Assets/Z3/connectors/brother.png")
const BUMPER_TOP = preload("res://Assets/Z3/connectors/bumper-u.png")
const BUMPER_BOTTOM = preload("res://Assets/Z3/connectors/bumper-d.png")
const SUPERBUNNY_TOP = preload("res://Assets/Z3/connectors/bunny-u.png")
const SUPERBUNNY_BOTTOM = preload("res://Assets/Z3/connectors/bunny-d.png")
const SHIT_FAIRY = preload("res://Assets/Z3/connectors/fairy_ascension.png")
const DANCING_LADY = preload("res://Assets/Z3/connectors/granny.png")
const BAT_CAVE = preload("res://Assets/Z3/connectors/keese_cave.png")
const LIBRARY = preload("res://Assets/Z3/connectors/library.png")
const ZELDA = preload("res://Assets/Z3/connectors/maiden.png")
const CAVE = preload("res://Assets/Z3/connectors/mountain_cave.png")
const DARK_CAVE = preload("res://Assets/Z3/connectors/mountain_cave_back.png")
const HOOKSHOT_CAVE = preload("res://Assets/Z3/connectors/hookshotcave.png")
const OLD_SAVE_FRONT = preload("res://Assets/Z3/connectors/oldman-d.png")
const OLD_SAVE_BACK = preload("res://Assets/Z3/connectors/oldman-u.png")
const PARADOX_MID = preload("res://Assets/Z3/connectors/paradox-bl.png")
const PARADOX_BOTTOM = preload("res://Assets/Z3/connectors/paradox-br.png")
const PARADOX_TOP = preload("res://Assets/Z3/connectors/paradox-u.png")
const WITCH = preload("res://Assets/Z3/connectors/potion_shop.png")
const SICK_KID = preload("res://Assets/Z3/connectors/sick_kid.png")
const BLACKSMITH = preload("res://Assets/Z3/connectors/smith.png")
const SPEC_BOTTOM = preload("res://Assets/Z3/connectors/spec-br.png")
const SPEC_TOP = preload("res://Assets/Z3/connectors/spec-u.png")
const SPEC_MID = preload("res://Assets/Z3/connectors/spec-bl.png")
const SPIKE = preload("res://Assets/Z3/connectors/spike.png")
const SPIRAL_BOTTOM = preload("res://Assets/Z3/connectors/spiral-d.png")
const SPIRAL_TOP = preload("res://Assets/Z3/connectors/spiral-u.png")
const SAHAS = preload("res://Assets/Z3/connectors/sriracha.png")
const AT = preload("res://Assets/Z3/dungeons/at.png")
const DP_MAIN = preload("res://Assets/Z3/dungeons/dp-d.png")
const DP_LEFT = preload("res://Assets/Z3/dungeons/dp-l.png")
const DP_TOP = preload("res://Assets/Z3/dungeons/dp-u.png")
const DP_RIGHT = preload("res://Assets/Z3/dungeons/dp-r.png")
const EP = preload("res://Assets/Z3/dungeons/ep.png")
const GANON = preload("res://Assets/Z3/dungeons/ganon.png")
const GT = preload("res://Assets/Z3/dungeons/gt.png")
const HC_MAIN = preload("res://Assets/Z3/dungeons/hc-d.png")
const HC_LEFT = preload("res://Assets/Z3/dungeons/hc-l.png")
const HC_RIGHT = preload("res://Assets/Z3/dungeons/hc-r.png")
const ICE = preload("res://Assets/Z3/dungeons/ip.png")
const MM = preload("res://Assets/Z3/dungeons/mm.png")
const POD = preload("res://Assets/Z3/dungeons/pd.png")
const SP = preload("res://Assets/Z3/dungeons/sp.png")
const SW = preload("res://Assets/Z3/dungeons/sw.png")
const TOH = preload("res://Assets/Z3/dungeons/th.png")
const TR_MAIN = preload("res://Assets/Z3/dungeons/tr.png")
const TR_LEFT = preload("res://Assets/Z3/dungeons/tr-l.png")
const TR_RIGHT = preload("res://Assets/Z3/dungeons/tr-r.png")
const TR_WIN = preload("res://Assets/Z3/dungeons/tr-u.png")
const TT = preload("res://Assets/Z3/dungeons/tt.png")
const AGINAH = preload("res://Assets/Z3/entrances/aginah.png")
const BLIND = preload("res://Assets/Z3/entrances/blind.png")
const BONKROCKS = preload("res://Assets/Z3/entrances/bonkrocks.png")
const BREWERY = preload("res://Assets/Z3/entrances/brewery.png")
const CAVE_45 = preload("res://Assets/Z3/entrances/cave45.png")
const CHECKERBOARD = preload("res://Assets/Z3/entrances/checkerboard.png")
const CHESTGAME = preload("res://Assets/Z3/entrances/chestgame.png")
const CHICKEN_HOUSE = preload("res://Assets/Z3/entrances/chickenhouse.png")
const CHOUSE = preload("res://Assets/Z3/entrances/chouse.png")
const DAM = preload("res://Assets/Z3/entrances/dam.png")
const GRAVEYARD_LEDGE = preload("res://Assets/Z3/entrances/graveyardledge.png")
const HAMMERPEGS = preload("res://Assets/Z3/entrances/hammerpegs.png")
const HYPECAVE = preload("res://Assets/Z3/entrances/hypecave.png")
const KINGSTOMB = preload("res://Assets/Z3/entrances/kingstomb.png")
const LUCK_FAIRY = preload("res://Assets/Z3/entrances/luckfairy.png")
const MIMIC = preload("res://Assets/Z3/entrances/mimic.png")
const MOLDORM = preload("res://Assets/Z3/entrances/minimoldorm.png")
const MIRESHED = preload("res://Assets/Z3/entrances/mireshed.png")
const PYRAMID = preload("res://Assets/Z3/entrances/pyramid.png")
const WATERFALL = preload("res://Assets/Z3/entrances/waterfall.png")
const BOOTS = preload("res://Assets/Z3/items/boots.png")
const GLOVES = preload("res://Assets/Z3/items/glove.png")
const FLIPPERS = preload("res://Assets/Z3/items/flippers.png")
const SWORD = preload("res://Assets/Z3/items/sword.png")
const PEARL = preload("res://Assets/Z3/items/mearl.png")
const BIGKEY = preload("res://Assets/Z3/items/big_key.png")
const BOW = preload("res://Assets/Z3/items/bow.png")
const HOOKSHOT = preload("res://Assets/Z3/items/hookshot.png")
const FIREROD = preload("res://Assets/Z3/items/fire_rod.png")
const ICEROD = preload("res://Assets/Z3/items/ice_rod.png")
const POWDER = preload("res://Assets/Z3/items/powder.png")
const SMALLKEY = preload("res://Assets/Z3/items/small_key.png")
const BOMBOS = preload("res://Assets/Z3/items/bombos.png")
const LAMP = preload("res://Assets/Z3/items/lamp.png")
const HAMMER = preload("res://Assets/Z3/items/hammer.png")
const SOMARIA = preload("res://Assets/Z3/items/somaria.png")
const BYRNACAPE = preload("res://Assets/Z3/items/byrna_cape.png")

const Z3ITEM = [preload("res://Assets/Z3/items/0060.png"),preload("res://Assets/Z3/items/bow.png"),preload("res://Assets/Z3/items/boom.png"),preload("res://Assets/Tracker/0002.png"),\
preload("res://Assets/Tracker/0004.png"),preload("res://Assets/Tracker/0046.png"),preload("res://Assets/Tracker/0005.png"),\
preload("res://Assets/Tracker/0006.png"),preload("res://Assets/Tracker/0007.png"),preload("res://Assets/Tracker/0008.png"),\
preload("res://Assets/Tracker/0009.png"),preload("res://Assets/Tracker/0010.png"),preload("res://Assets/Tracker/0011.png"),\
preload("res://Assets/Tracker/0012.png"),preload("res://Assets/Tracker/0047.png"),preload("res://Assets/Tracker/0014.png"),\
preload("res://Assets/Tracker/bottle.png"),preload("res://Assets/Tracker/0015.png"),preload("res://Assets/Tracker/0016.png"),\
preload("res://Assets/Tracker/0017.png"),preload("res://Assets/Tracker/0018.png"),preload("res://Assets/Tracker/0020.png"),\
preload("res://Assets/Tracker/0019.png"),preload("res://Assets/Tracker/0021.png"),preload("res://Assets/Tracker/0022.png"),\
preload("res://Assets/Tracker/0038.png"),preload("res://Assets/Tracker/BigKey.png"),preload("res://Assets/Tracker/SmallKey2.png"),preload("res://Assets/Z3/items/rupee.png")]

const ITEM_SIZE = 44
const ITEM_GAP = 2
const ITEM_SPACING = 46
const DUNGEON_START_X = 2
const START_Y = 752
const CONNECTOR_START_X = 2
const ENTRANCE_START_X = 344
const ITEM_START_X = 504

@onready var overworld_map = $OverworldMap
@onready var ERmap = $OverworldMap/EntranceRando
@onready var standard = $OverworldMap/Standard

var boundary
var undoList = []

var m1door
var z1door
var smdoors = []

func filterParents(parent,idMatch):
	if parent.id.begins_with(idMatch):
		return true
	return false
	
func _ready():
	boundary = Rect2(overworld_map.position, overworld_map.get_rect().size + overworld_map.position)
	create_ER_map()
	create_Standard_map()
	
func create_Standard_map():
	# Dungeon Parents
	_make_parent_ST(ZELDA,2,752,"HC Zelda")
	_make_parent_ST(HC_LEFT,48,752,"HC Left")
	_make_parent_ST(HC_MAIN,94,752,"HC Main")
	_make_parent_ST(HC_RIGHT,140,752,"HC Right")
	standard.get_child(0).pair(standard.get_children().filter(filterParents.bind("HC")))
	_make_parent_ST(EP,186,752,"EP")
	_make_parent_ST(DP_LEFT,232,752,"DP Left")
	_make_parent_ST(DP_MAIN,278,752,"DP Main")
	_make_parent_ST(DP_RIGHT,324,752,"DP Right")
	_make_parent_ST(DP_TOP,370,752,"DP Top")
	standard.get_child(5).pair(standard.get_children().filter(filterParents.bind("DP")))
	_make_parent_ST(TOH,416,752,"Hera")
	_make_parent_ST(AT,462,752,"Aga Tower")
	_make_parent_ST(POD,508,752,"POD")
	_make_parent_ST(SP,554,752,"Swamp")
	_make_parent_ST(SW,600,752,"Skull Woods")
	_make_parent_ST(TT,646,752,"Thieves")
	_make_parent_ST(ICE,692,752,"Ice Palace")
	_make_parent_ST(MM,738,752,"Mire")
	_make_parent_ST(TR_LEFT,784,752,"TR Left")
	_make_parent_ST(TR_MAIN,830,752,"TR Main")
	_make_parent_ST(TR_RIGHT,876,752,"TR Right")
	_make_parent_ST(TR_WIN,924,752,"TR Top")
	standard.get_child(18).pair(standard.get_children().filter(filterParents.bind("TR")))
	_make_parent_ST(GT,970,752,"GT")
	_make_parent_ST(GANON,1016,752,"Ganon")
	
	# Connector Parents
	_make_parent_ST(SPEC_TOP,2,798,"Spec Top")
	_make_parent_ST(SPEC_MID,2,844,"Spec Mid")
	_make_parent_ST(SPEC_BOTTOM,2,890,"Spec Bottom")
	standard.get_child(24).pair(standard.get_children().filter(filterParents.bind("Spec")))
	_make_parent_ST(PARADOX_TOP,48,798,"Paradox Top")
	_make_parent_ST(PARADOX_MID,48,844,"Paradox Mid")
	_make_parent_ST(PARADOX_BOTTOM,48,890,"Paradox Bottom")
	standard.get_child(27).pair(standard.get_children().filter(filterParents.bind("Paradox")))
	_make_parent_ST(CAVE,94,798,"Cave")
	_make_parent_ST(DARK_CAVE,94,844,"Cave Dark")
	_make_parent_ST(BAT_CAVE,94,890,"Cave Bat")
	standard.get_child(30).pair(standard.get_children().filter(filterParents.bind("Cave")))
	_make_parent_ST(OLD_SAVE_BACK,140,798,"Old Man Save Top")
	_make_parent_ST(OLD_SAVE_FRONT,140,844,"Old Man Save Bottom")
	standard.get_child(33).pair(standard.get_children().filter(filterParents.bind("Old Man Save")))
	_make_parent_ST(SHIT_FAIRY,140,890,"Fairy Cave")
	_make_parent_ST(SUPERBUNNY_TOP,186,798,"Superbunny Top")
	_make_parent_ST(SUPERBUNNY_BOTTOM,186,844,"Superbunny Bottom")
	standard.get_child(36).pair(standard.get_children().filter(filterParents.bind("Superbunny")))
	_make_parent_ST(HOOKSHOT_CAVE,186,890,"Hookshot Cave")
	_make_parent_ST(BUMPER_TOP,232,798,"Bumper Top")
	_make_parent_ST(BUMPER_BOTTOM,232,844,"Bumper Bottom")
	standard.get_child(39).pair(standard.get_children().filter(filterParents.bind("Bumper")))
	_make_parent_ST(BROTHER,232,890,"Brothers")
	_make_parent_ST(SPIRAL_TOP,278,798,"Spiral Top")
	_make_parent_ST(SPIRAL_BOTTOM,278,844,"Spiral Bottom")
	standard.get_child(42).pair(standard.get_children().filter(filterParents.bind("Spiral")))
	_make_parent_ST(DANCING_LADY,278,890,"Brothers")
	
	# Single Entrance Parents
	_make_parent_ST(SICK_KID,344,798,"Sick Kid")
	_make_parent_ST(MIMIC,344,844,"Mimic Cave")
	_make_parent_ST(SPIKE,344,890,"Spike Cave")
	_make_parent_ST(SAHAS,390,798,"Sahas")
	_make_parent_ST(WITCH,390,844,"Witch")
	_make_parent_ST(DAM,390,890,"Dam")
	_make_parent_ST(CHECKERBOARD,436,798,"Checkerboard")
	_make_parent_ST(BLACKSMITH,436,844,"Blacksmith")
	_make_parent_ST(BIG_BOMB,436,890,"Big Bomb")
	
	# Item Parents
	_make_parent_ST(BOW,ITEM_START_X + 0 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Bow")
	_make_parent_ST(HOOKSHOT,ITEM_START_X + 1 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Hookshot")
	_make_parent_ST(BOOTS,ITEM_START_X + 0 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Boots")
	_make_parent_ST(BOMBOS,ITEM_START_X + 0 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING,"Bombos")
	_make_parent_ST(GLOVES,ITEM_START_X + 1 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Gloves")
	_make_parent_ST(LAMP,ITEM_START_X + 1 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING,"Lamp")
	_make_parent_ST(FLIPPERS,ITEM_START_X + 2 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Flippers")
	_make_parent_ST(FIREROD,ITEM_START_X + 2 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Fire Rod")
	_make_parent_ST(HAMMER,ITEM_START_X + 2 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING,"Hammer")
	_make_parent_ST(SWORD,ITEM_START_X + 3 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Sword")
	_make_parent_ST(ICEROD,ITEM_START_X + 3 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Ice Rod")
	_make_parent_ST(SOMARIA,ITEM_START_X + 3 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING,"Somaria")
	_make_parent_ST(PEARL,ITEM_START_X + 4 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Pearl")
	_make_parent_ST(POWDER,ITEM_START_X + 4 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Powder")
	_make_parent_ST(BYRNACAPE,ITEM_START_X + 4 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING,"Byrna Cape")
	_make_parent_ST(BIGKEY,ITEM_START_X + 5 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Big Key")
	_make_parent_ST(SMALLKEY,ITEM_START_X + 5 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Small Key")
	_make_scrollable_parent_ST(Z3ITEM,ITEM_START_X + 5 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING)
	_make_scrollable_parent_ST($"../Z1".Z1ITEM,ITEM_START_X + 6 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING)
	_make_scrollable_parent_ST($"../M1".M1ITEM,ITEM_START_X + 6 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING)
	_make_scrollable_parent_ST($"../SM".SMITEM,ITEM_START_X + 6 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING)
	
	
	# Light World Items
	_make_marker_ST(2,25,26,"Pedestal")
	_make_marker_ST(2,85,58,"Mushroom")
	_make_marker_ST(2,309,4,"Ether Tablet")
	_make_marker_ST(2,375,58,"Spec Rock Island")
	_make_marker_ST(2,312,167,"Old Man")
	_make_marker_ST(2,602,5,"Floating Island")
	_make_marker_ST(2,706,95,"Zora Ledge")
	_make_marker_ST(2,723,95,"King Zora")
	_make_marker_ST(2,64,340,"Bottle Merchant")
	_make_marker_ST(2,16,518,"Maze Race")
	_make_marker_ST(2,212,488,"Dig Spot")
	_make_marker_ST(2,525,515,"Hobo")
	_make_marker_ST(2,11,680,"Desert Ledge")
	_make_marker_ST(2,158,681,"Bombos Tablet")
	_make_marker_ST(2,249,667,"Purple Chest")
	_make_marker_ST(2,329,691,"Flooded Dam")
	_make_marker_ST(2,538,614,"Lake Hylia Island")
	# Dark World Items
	_make_marker_ST(2,997,108,"Bumper Cave")
	_make_marker_ST(2,1415,120,"Catfish")
	_make_marker_ST(2,1180,331,"Pyramid")
	_make_marker_ST(2,787,507,"Digging Game")
	_make_marker_ST(2,975,506,"Stumpy")
	# Light World Entrances
	_make_marker_ST(2,135,92,"LW Drop")
	_make_marker_ST(2,218,48,"Lumberjack Drop")
	_make_marker_ST(2,286,214,"Bonk Rocks")
	_make_marker_ST(2,422,200,"Graveyard Ledge")
	_make_marker_ST(2,444,215,"Kings Tomb")
	_make_marker_ST(2,359,102,"Spec Drop")
	_make_marker_ST(1,414,19,"Hera")
	_make_marker_ST(2,592,63,"Spiral Top")
	_make_marker_ST(2,641,155,"Paradox Middle")
	_make_marker_ST(2,626,63,"Mimic Cave")
	_make_marker_ST(2,669,96,"Waterfall")
	_make_marker_ST(2,593,245,"Witch")
	_make_marker_ST(2,602,334,"Sahasrahla")
	_make_marker_ST(1,713,286,"Eastern")
	_make_marker_ST(2,10,313,"Kak Well")
	_make_marker_ST(2,89,309,"Blinds Hut")
	_make_marker_ST(2,67,399,"Chicken Hut")
	_make_marker_ST(2,111,398,"Sick Kid")
	_make_marker_ST(2,114,418,"Tavern Back")
	_make_marker_ST(2,222,392,"Blacksmith")
	_make_marker_ST(2,236,416,"Magic Bat")
	_make_marker_ST(2,110,489,"Library")
	_make_marker_ST(1,368,294,"Aga Tower")
	_make_marker_ST(1,368,323,"Hyrule")
	_make_marker_ST(2,440,310,"Uncle")
	_make_marker_ST(2,404,512,"Links House")
	_make_marker_ST(2,194,613,"Cave 45")
	_make_marker_ST(2,345,697,"Dam")
	_make_marker_ST(2,142,612,"Aginahs Cave")
	_make_marker_ST(1,49,591,"Desert Main")
	_make_marker_ST(2,125,578,"Checkerboard")
	_make_marker_ST(2,482,698,"Mini Moldorm")
	_make_marker_ST(2,662,570,"Ice Rod Cave")
	# Dark World Entrances
	_make_marker_ST(1,771,32,"Skull Woods")
	_make_marker_ST(2,782,345,"Chest Game")
	_make_marker_ST(1,838,359,"Thieves Town")
	_make_marker_ST(2,900,356,"C Shape")
	_make_marker_ST(2,826,433,"Brewery")
	_make_marker_ST(2,981,449,"Hammer Pegs")
	_make_marker_ST(2,1173,104,"Spike Cave")
	_make_marker_ST(1,1166,9,"Ganons Tower")
	_make_marker_ST(2,1368,45,"Hookshot Cave Bottom")
	_make_marker_ST(2,1390,42,"Superbunny Top")
	_make_marker_ST(1,1450,55,"TR Main")
	_make_marker_ST(2,1094,360,"Pyramid Fairy")
	_make_marker_ST(1,1464,290,"Palace of Darkness")
	_make_marker_ST(2,1192,579,"Hype Cave")
	_make_marker_ST(1,1095,698,"Swamp")
	_make_marker_ST(1,1341,642,"Ice Palace")
	_make_marker_ST(1,1095,698,"Swamp")
	_make_marker_ST(1,799,598,"Misery Mire")
	_make_marker_ST(2,773,597,"Mire Shed")
	
func create_ER_map():
	# Dungeon Parents
	_make_parent(ZELDA,2,752,"HC Zelda")
	_make_parent(HC_LEFT,48,752,"HC Left")
	_make_parent(HC_MAIN,94,752,"HC Main")
	_make_parent(HC_RIGHT,140,752,"HC Right")
	ERmap.get_child(0).pair(ERmap.get_children().filter(filterParents.bind("HC")))
	_make_parent(EP,186,752,"EP")
	_make_parent(DP_LEFT,232,752,"DP Left")
	_make_parent(DP_MAIN,278,752,"DP Main")
	_make_parent(DP_RIGHT,324,752,"DP Right")
	_make_parent(DP_TOP,370,752,"DP Top")
	ERmap.get_child(5).pair(ERmap.get_children().filter(filterParents.bind("DP")))
	_make_parent(TOH,416,752,"Hera")
	_make_parent(AT,462,752,"Aga Tower")
	_make_parent(POD,508,752,"POD")
	_make_parent(SP,554,752,"Swamp")
	_make_parent(SW,600,752,"Skull Woods")
	_make_parent(TT,646,752,"Thieves")
	_make_parent(ICE,692,752,"Ice Palace")
	_make_parent(MM,738,752,"Mire")
	_make_parent(TR_LEFT,784,752,"TR Left")
	_make_parent(TR_MAIN,830,752,"TR Main")
	_make_parent(TR_RIGHT,876,752,"TR Right")
	_make_parent(TR_WIN,924,752,"TR Top")
	ERmap.get_child(18).pair(ERmap.get_children().filter(filterParents.bind("TR")))
	_make_parent(GT,970,752,"GT")
	_make_parent(GANON,1016,752,"Ganon")
	
	# Connector Parents
	_make_parent(SPEC_TOP,2,798,"Spec Top")
	_make_parent(SPEC_MID,2,844,"Spec Mid")
	_make_parent(SPEC_BOTTOM,2,890,"Spec Bottom")
	ERmap.get_child(24).pair(ERmap.get_children().filter(filterParents.bind("Spec")))
	_make_parent(PARADOX_TOP,48,798,"Paradox Top")
	_make_parent(PARADOX_MID,48,844,"Paradox Mid")
	_make_parent(PARADOX_BOTTOM,48,890,"Paradox Bottom")
	ERmap.get_child(27).pair(ERmap.get_children().filter(filterParents.bind("Paradox")))
	_make_parent(CAVE,94,798,"Cave")
	_make_parent(DARK_CAVE,94,844,"Cave Dark")
	_make_parent(BAT_CAVE,94,890,"Cave Bat")
	ERmap.get_child(30).pair(ERmap.get_children().filter(filterParents.bind("Cave")))
	_make_parent(OLD_SAVE_BACK,140,798,"Old Man Save Top")
	_make_parent(OLD_SAVE_FRONT,140,844,"Old Man Save Bottom")
	ERmap.get_child(33).pair(ERmap.get_children().filter(filterParents.bind("Old Man Save")))
	_make_parent(SHIT_FAIRY,140,890,"Fairy Cave")
	_make_parent(SUPERBUNNY_TOP,186,798,"Superbunny Top")
	_make_parent(SUPERBUNNY_BOTTOM,186,844,"Superbunny Bottom")
	ERmap.get_child(36).pair(ERmap.get_children().filter(filterParents.bind("Superbunny")))
	_make_parent(HOOKSHOT_CAVE,186,890,"Hookshot Cave")
	_make_parent(BUMPER_TOP,232,798,"Bumper Top")
	_make_parent(BUMPER_BOTTOM,232,844,"Bumper Bottom")
	ERmap.get_child(39).pair(ERmap.get_children().filter(filterParents.bind("Bumper")))
	_make_parent(BROTHER,232,890,"Brothers")
	_make_parent(SPIRAL_TOP,278,798,"Spiral Top")
	_make_parent(SPIRAL_BOTTOM,278,844,"Spiral Bottom")
	ERmap.get_child(42).pair(ERmap.get_children().filter(filterParents.bind("Spiral")))
	_make_parent(DANCING_LADY,278,890,"Brothers")
	
	# Single Entrance Parents
	_make_parent(SICK_KID,344,798,"Sick Kid")
	_make_parent(MIMIC,344,844,"Mimic Cave")
	_make_parent(SPIKE,344,890,"Spike Cave")
	_make_parent(SAHAS,390,798,"Sahas")
	_make_parent(WITCH,390,844,"Witch")
	_make_parent(DAM,390,890,"Dam")
	_make_parent(CHECKERBOARD,436,798,"Checkerboard")
	_make_parent(BLACKSMITH,436,844,"Blacksmith")
	_make_parent(BIG_BOMB,436,890,"Big Bomb")
	
	# Item Parents
	_make_parent(BOOTS,ITEM_START_X + 0 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Boots")
	_make_parent(BOW,ITEM_START_X + 0 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Bow")
	_make_parent(BOMBOS,ITEM_START_X + 0 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING,"Bombos")
	_make_parent(GLOVES,ITEM_START_X + 1 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Gloves")
	_make_parent(HOOKSHOT,ITEM_START_X + 1 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Hookshot")
	_make_parent(LAMP,ITEM_START_X + 1 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING,"Lamp")
	_make_parent(FLIPPERS,ITEM_START_X + 2 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Flippers")
	_make_parent(FIREROD,ITEM_START_X + 2 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Fire Rod")
	_make_parent(HAMMER,ITEM_START_X + 2 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING,"Hammer")
	_make_parent(SWORD,ITEM_START_X + 3 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Sword")
	_make_parent(ICEROD,ITEM_START_X + 3 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Ice Rod")
	_make_parent(SOMARIA,ITEM_START_X + 3 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING,"Somaria")
	_make_parent(PEARL,ITEM_START_X + 4 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Pearl")
	_make_parent(POWDER,ITEM_START_X + 4 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Powder")
	_make_parent(BYRNACAPE,ITEM_START_X + 4 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING,"Byrna Cape")
	_make_parent(BIGKEY,ITEM_START_X + 5 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING,"Big Key")
	_make_parent(SMALLKEY,ITEM_START_X + 5 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING,"Small Key")
	_make_scrollable_parent(Z3ITEM,ITEM_START_X + 5 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING)
	_make_scrollable_parent($"../Z1".Z1ITEM,ITEM_START_X + 6 * ITEM_SPACING,START_Y + 1 * ITEM_SPACING)
	_make_scrollable_parent($"../M1".M1ITEM,ITEM_START_X + 6 * ITEM_SPACING,START_Y + 2 * ITEM_SPACING)
	_make_scrollable_parent($"../SM".SMITEM,ITEM_START_X + 6 * ITEM_SPACING,START_Y + 3 * ITEM_SPACING)
	
	
	# Light World Items
	_make_marker(2,25,26,"Pedestal")
	_make_marker(2,85,58,"Mushroom")
	_make_marker(2,309,4,"Ether Tablet")
	_make_marker(2,375,58,"Spec Rock Island")
	_make_marker(2,312,167,"Old Man")
	_make_marker(2,602,5,"Floating Island")
	_make_marker(2,706,95,"Zora Ledge")
	_make_marker(2,723,95,"King Zora")
	_make_marker(2,64,340,"Bottle Merchant")
	_make_marker(2,16,518,"Maze Race")
	_make_marker(2,212,488,"Dig Spot")
	_make_marker(2,525,515,"Hobo")
	_make_marker(2,11,680,"Desert Ledge")
	_make_marker(2,158,681,"Bombos Tablet")
	_make_marker(2,249,667,"Purple Chest")
	_make_marker(2,329,691,"Flooded Dam")
	_make_marker(2,538,614,"Lake Hylia Island")
	# Dark World Items
	_make_marker(2,997,108,"Bumper Cave")
	_make_marker(2,1415,120,"Catfish")
	_make_marker(2,1180,331,"Pyramid")
	_make_marker(2,787,507,"Digging Game")
	_make_marker(2,975,506,"Stumpy")
	# Light World Entrances
	_make_marker(1,132,5,"LW Tunnel")
	_make_marker(1,135,92,"LW Drop")
	_make_marker(1,218,48,"Lumberjack Drop")
	_make_marker(1,245,40,"Lumberjack Shop") #M1 connection
	m1door = ERmap.get_child(-1)
	m1door.hide()
	_make_marker(1,262,108,"LW Bumper Top")
	_make_marker(1,259,127,"LW Bumper Bottom")
	_make_marker(1,135,237,"Kak Fortune Teller") #Z1 connection 
	z1door = ERmap.get_child(-1)
	z1door.hide()
	_make_marker(1,286,214,"Bonk Rocks")
	_make_marker(1,382,213,"Sanctuary Drop")
	_make_marker(1,422,200,"Graveyard Ledge")
	_make_marker(1,444,215,"Kings Tomb")
	_make_marker(1,473,225,"Shit Fairy Drop")
	_make_marker(1,297,135,"Old Man Back")
	_make_marker(1,330,171,"Old Man SQ Front")
	_make_marker(1,394,114,"Old Man SQ Back") #SM connection 
	smdoors.append(ERmap.get_child(-1))
	ERmap.get_child(-1).hide()
	_make_marker(1,289,96,"DM Exit")
	_make_marker(1,334,96,"Spec Return")
	_make_marker(1,359,102,"Spec Drop")
	_make_marker(1,359,70,"Spec View")
	_make_marker(1,414,19,"Hera")
	_make_marker(1,592,63,"Spiral Top")
	_make_marker(1,590,90,"Spiral Bottom")
	_make_marker(1,607,79,"Shit Fairy Top")
	_make_marker(1,607,97,"Shit Fairy Bottom")
	_make_marker(1,624,103,"DM Shop")
	_make_marker(1,641,103,"Paradox Bottom")
	_make_marker(1,641,155,"Paradox Middle")
	_make_marker(1,637,42,"Paradox Top")
	_make_marker(1,626,63,"Mimic Cave")
	_make_marker(1,669,96,"Waterfall")
	_make_marker(1,593,245,"Witch")
	_make_marker(1,602,334,"Sahasrahla")
	_make_marker(1,713,286,"Eastern")
	_make_marker(1,611,478,"LW Line of Trees")
	_make_marker(1,727,519,"LW Flute 5")
	_make_marker(1,10,313,"Kak Well")
	_make_marker(1,89,309,"Blinds Hut")
	_make_marker(1,106,309,"Dancing Left")
	_make_marker(1,121,309,"Dancing Right")
	_make_marker(1,32,344,"Left Snitch")
	_make_marker(1,148,356,"Right Snitch")
	_make_marker(1,67,399,"Chicken Hut")
	_make_marker(1,111,398,"Sick Kid")
	_make_marker(1,146,395,"Grass House")
	_make_marker(1,114,418,"Tavern Back")
	_make_marker(1,114,442,"Tavern Front")
	_make_marker(1,76,433,"Kak Shop")
	_make_marker(1,13,440,"Bomb Farm")
	_make_marker(1,222,392,"Blacksmith")
	_make_marker(1,236,416,"Magic Bat")
	_make_marker(1,110,489,"Library")
	_make_marker(1,76,534,"Maze Left")
	_make_marker(1,99,534,"Maze Right")
	_make_marker(1,154,521,"LW Archery")
	_make_marker(1,330,284,"Hyrule Left")
	_make_marker(1,407,284,"Hyrule Right")
	_make_marker(1,368,294,"Aga Tower")
	_make_marker(1,368,323,"Hyrule")
	_make_marker(1,440,306,"Uncle Drop")
	_make_marker(1,347,483,"LW Links Bonk")
	_make_marker(1,404,512,"Links House")
	_make_marker(1,194,613,"Cave 45")
	_make_marker(1,442,579,"LW Hype")
	_make_marker(1,345,697,"Dam")
	_make_marker(1,228,713,"Desert Rock")
	_make_marker(1,200,662,"Desert Fairy")
	_make_marker(1,142,612,"Aginahs Cave")
	_make_marker(1,49,591,"Desert Main")
	_make_marker(1,20,591,"Desert Left")
	_make_marker(1,78,591,"Desert Right")
	_make_marker(1,49,567,"Desert Top")
	_make_marker(1,125,578,"Checkerboard")
	_make_marker(1,482,698,"Mini Moldorm")
	_make_marker(1,480,596,"Hylia Fortune") #SM connection
	smdoors.append(ERmap.get_child(-1))
	ERmap.get_child(-1).hide()
	_make_marker(1,538,570,"Hylia Shop")
	_make_marker(1,589,635,"Capacity Fairy")
	_make_marker(1,662,570,"Ice Rod Cave")
	_make_marker(1,671,588,"Ice Rod Rock")
	_make_marker(1,682,570,"Ice Rod Fairy")
	# Dark World Entrances
	_make_marker(1,771,32,"Skull Woods")
	_make_marker(1,995,37,"DW Lumberjack")
	_make_marker(1,1013,110,"Bumper Top")
	_make_marker(1,1010,127,"Bumper Bottom")
	_make_marker(1,884,238,"VoO Fortune")
	_make_marker(1,1089,201,"Dark Sanctuary")
	_make_marker(1,782,345,"Chest Game")
	_make_marker(1,838,359,"Thieves Town")
	_make_marker(1,900,356,"C Shape")
	_make_marker(1,826,433,"Brewery")
	_make_marker(1,896,394,"Hammer House")
	_make_marker(1,992,339,"Curiosity Shop")
	_make_marker(1,981,449,"Hammer Pegs")
	_make_marker(1,1047,136,"DWDM Bottom")
	_make_marker(1,1173,104,"Spike Cave")
	_make_marker(1,1166,9,"Ganons Tower")
	_make_marker(1,1343,6,"Hookshot Cave Top")
	_make_marker(1,1368,45,"Hookshot Cave Bottom")
	_make_marker(1,1390,42,"Superbunny Top")
	_make_marker(1,1373,104,"Superbunny Bottom")
	_make_marker(1,1390,104,"EDWDM Shop")
	_make_marker(1,1342,63,"TR Connector Left")
	_make_marker(1,1377,63,"TR Connector Right")
	_make_marker(1,1359,82,"Laser Bridge")
	_make_marker(1,1450,55,"TR Main")
	_make_marker(1,1346,248,"DW Potion Shop")
	_make_marker(1,1116,301,"Ganon Drop")
	_make_marker(1,1094,360,"Pyramid Fairy")
	_make_marker(1,1464,290,"Palace of Darkness")
	_make_marker(1,1381,372,"Pod Mid")
	_make_marker(1,1363,480,"DW Line of Trees")
	_make_marker(1,1480,520,"DW Flute 5")
	_make_marker(1,904,521,"Archery Game")
	_make_marker(1,1098,484,"DW Bonk Rocks")
	_make_marker(1,1153,512,"Big Bomb Shop")
	_make_marker(1,1192,579,"Hype Cave")
	_make_marker(1,1095,698,"Swamp")
	_make_marker(1,1230,597,"DW Hylia Fortune")
	_make_marker(1,1341,642,"Ice Palace")
	_make_marker(1,1095,698,"Swamp")
	_make_marker(1,1412,570,"DW Ice Rod Cave")
	_make_marker(1,1421,588,"DW Ice Rod Rock")
	_make_marker(1,1432,570,"DW Ice Rod Fairy") #SM connection
	smdoors.append(ERmap.get_child(-1))
	ERmap.get_child(-1).hide()
	_make_marker(1,799,598,"Misery Mire")
	_make_marker(1,773,597,"Mire Shed")
	_make_marker(1,826,597,"Mire Right") #SM connection
	smdoors.append(ERmap.get_child(-1))
	ERmap.get_child(-1).hide()
	_make_marker(1,893,614,"Mire Hint")

func _make_marker(type, x, y, id):
	var marker = Marker.new(type,x,y,id, null, 3)
	#marker.scale = Vector2(1.5,1.5)
	marker.position -= Vector2(3,3)
	ERmap.add_child(marker)

func _make_parent(texture,x,y,id):
	var poi = ParentPOI.new(texture,x,y,id, boundary , 3)
	ERmap.add_child(poi)

func _make_scrollable_parent(texture,x,y):
	var poi = ScrollableParent.new(texture,x,y, boundary , 3)
	ERmap.add_child(poi)
	
func _make_marker_ST(type, x, y, id):
	var marker = Marker.new(type,x,y,id, null, 3)
	#marker.scale = Vector2(1.5,1.5)
	marker.position -= Vector2(3,3)
	standard.add_child(marker)

func _make_parent_ST(texture,x,y,id):
	var poi = ParentPOI.new(texture,x,y,id, boundary, 3)
	standard.add_child(poi)
	
func _make_scrollable_parent_ST(texture,x,y):
	var poi = ScrollableParent.new(texture,x,y, boundary, 3)
	standard.add_child(poi)
